org: zhaoelton
app: leetcode
service: item-tracker-api


frameworkVersion: '2'
custom:
  tableName: 'leetcode-tracker-${self:provider.stage}'
  wsgi:
    app: app.app

package:
  individually: true
  exclude:
    - venv/**
    - node_modules/**


provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  stage: dev
  region: us-east-1

  environment:
    INGESTION_KEY: ${param:INGESTION_KEY}
    TABLE_NAME: ${param:TABLE_NAME}
    REGION: ${param:REGION}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: "arn:aws:dynamodb:us-east-1:*:*"


functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true # <-- CORS!
      - http:
          path: /{proxy+}
          method: ANY
          cors: true


plugins:
  - serverless-wsgi
  - serverless-python-requirements
